Issue#4: iOS информация
MAVIKE/yad-docs pull request #11
Opened 2021-03-09 11:45 UTC by timoninas

2021-03-09 18:56 UTC, vovac12 requested changes

2021-03-09 18:56 UTC, vovac12 commented on README.md
Нужно добавить регламенты кодирования для iOS

2021-03-12 21:10 UTC, architectv approved these changes

2021-03-12 21:14 UTC, VolkovEgor approved these changes

2021-03-12 21:17 UTC, RyazMax commented
Closes #11

2021-03-12 21:18 UTC, RyazMax approved these changes

2021-03-12 21:21 UTC, vovac12 approved these changes

2021-03-12 21:21 UTC, merged